spring.application.name=project-manager

springdoc.swagger-ui.path=/swagger

# Jwt
application.security.jwt.secret-key=${JWT_SECRET_KEY:jx+kB9HbpSjRZsth9+hWGgxvSbxq3LiOU3tAC967oHQ=}
application.security.jwt.expiration=${JWT_EXPIRATION:900000}
application.security.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/projectmanager}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

