spring.application.name=project-manager
spring.profiles.active=dev
spring.jpa.open-in-view=false
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
application.security.swagger.enabled=true


# Jwt
application.security.jwt.secret-key=${JWT_SECRET_KEY:jx+kB9HbpSjRZsth9+hWGgxvSbxq3LiOU3tAC967oHQ=}
application.security.jwt.expiration=${JWT_EXPIRATION:900000}
application.security.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/projectmanager}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:change_me}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

application.security.cookie.secure=${COOKIE_SECURE:false}

application.admin.username=${ADMIN_USERNAME:admin@admin.com}
application.admin.password=${ADMIN_PASSWORD:admin123}

