spring.application.name=project-manager

springdoc.swagger-ui.path=/swagger

# Jwt ( secret-key tylko dla developmentu)
application.security.jwt.secret-key=jx+kB9HbpSjRZsth9+hWGgxvSbxq3LiOU3tAC967oHQ=
application.security.jwt.expiration=86400000